version: '3.8'

networks:
  hrms:
    external: true

services:
  postgres_db:
    image: postgres:latest
    container_name: hrms_db
    restart: always
    environment:
      - POSTGRES_DB=hrms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

    networks:
      - hrms

volumes:
  postgres_db:
    driver: local
